# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbomex < Formula
  desc "Binary distribution for homebrew."
  homepage "https://github.com/kchetans/sbomex"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.6/sbomex-darwin-amd64"
      sha256 "1bf135fbe783c537bf340992e78b4d744f0ad3484256bda3a93c5afa5473f5e5"

      def install
        bin.install "sbomex-darwin-amd64" => "sbomex-darwin-amd64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.6/sbomex-darwin-arm64"
      sha256 "74d9b55d87eab2b73bbab03fb08c5c83ad2206d57242337091f7b56281035b5e"

      def install
        bin.install "sbomex-darwin-arm64" => "sbomex-darwin-arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.6/sbomex-linux-amd64"
      sha256 "25e9387fb54b556d44f2d2fcb299580303df89e206ceb23f96d99aab31aab934"

      def install
        bin.install "sbomex-linux-amd64" => "sbomex-linux-amd64"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kchetans/sbomex/releases/download/v0.0.6/sbomex-linux-arm64"
      sha256 "a3dea24581c956737ef6950a87331fae0a30d67b9d2cf022eab6db24c1a4360a"

      def install
        bin.install "sbomex-linux-arm64" => "sbomex-linux-arm64"
      end
    end
  end
end
